#ifndef DEFINE_H
#define DEFINE_H

#define _USE_MATH_DEFINES

#include <d3d9.h>
#include <d3dx9.h>
#include <map> 
#include "Utils.h"
#include <fstream>
#include <iostream>
#include <string>
using namespace std;

// width height Screen
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 499 //448

#define ID_SPRITE_TILEMAP	50001

// parse
#define SCENE_SECTION_UNKNOWN -1
#define SCENE_SECTION_TEXTURES 2
#define SCENE_SECTION_SPRITES 3
#define SCENE_SECTION_ANIMATIONS 4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS	6
#define SCENE_SECTION_TILEMAP	7
#define SCENE_SECTION_LOADSIMON_0	8
#define SCENE_SECTION_LOADSIMON_1	9

// obj type
#define OBJECT_TYPE_SIMON	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_TORCH	2
#define OBJECT_TYPE_CANDLE	3
#define OBJECT_TYPE_STAIR	4
#define OBJECT_TYPE_BLACKKNIGHT 5
#define OBJECT_TYPE_ZOMBIEZONE 7
#define OBJECT_TYPE_SPECIALBRICK 8
#define OBJECT_TYPE_SPECIALBRICKSMALL 9
#define OBJECT_TYPE_BAT 10
#define OBJECT_TYPE_GHOSTZONE 11
#define OBJECT_TYPE_MOVINGBRICK 12
#define OBJECT_TYPE_HUNCHBACKZONE 13
#define OBJECT_TYPE_SKELETONZONE 14
#define OBJECT_TYPE_RAVENZONE 15
#define OBJECT_TYPE_HIDDENOBJECTCREATEBOSS 16
#define OBJECT_TYPE_HIDDENOBJECTBLOCKCAMERA 17
#define OBJECT_TYPE_HIDDENOBJECT 49
#define OBJECT_TYPE_PORTAL	50

// parse
#define MAX_SCENE_LINE 1024

// ANI_SET_ID
#define SIMON_ANI_SET_ID 1
#define BRICK_ANI_SET_ID 22
#define STAIRBRICK_ANI_SET_ID 23
#define TORCH_ANI_SET_ID 33
#define CANDLE_ANI_SET_ID 34
#define MORNINGSTAR_ANI_SET_ID 44
#define LARGEHEART_ANI_SET_ID 45
#define UPGRADEMORNINGSTAR_ANI_SET_ID 46
#define FONT_ANI_SET_ID 47
#define BOARD_ANI_SET_ID 48
#define DAGGER_ANI_SET_ID 49
#define BOARDHEALTH_ANI_SET_ID 50
#define FIREEFFECT_ANI_SET_ID 51
#define HITEFFECT_ANI_SET_ID 52
#define	MONNEY_ANI_SET_ID 53
#define SMALLHEART_ANI_SET_ID 54
#define ZOMBIE_ANI_SET_ID 56
#define BAT_ANI_SET_ID 57
#define HOLYWATERITEM_ANI_SET_ID 58
#define HOLYWATER_ANI_SET_ID 59
#define BROKENBRICK_ANI_SET_ID 60
#define CROWN_ANI_SET_ID 61
#define GHOST_ANI_SET_ID 62
#define STOPWATCHITEM_ANI_SET_ID 63
#define BOOMERANGITEM_ANI_SET_ID 64
#define BOOMERANG_ANI_SET_ID 65
#define AXEITEM_ANI_SET_ID 66
#define AXE_ANI_SET_ID 67
#define MOVINGBRICK_ANI_SET_ID 68
#define HUNCHBACK_ANI_SET_ID 69
#define BONE_ANI_SET_ID 70
#define SKELETON_ANI_SET_ID 71
#define RAVEN_ANI_SET_ID 72
#define PHANTOMBAT_ANI_SET_ID 73
#define REDBALL_ANI_SET_ID 74
#define EFFECT100_ANI_SET_ID 75
#define EFFECT1000_ANI_SET_ID 76

// define time create ghost
#define TIME_CREATE_GHOST 1000

// Clear state
#define CLEARSTATE_PROCESS_HEALTH 0 // xử lí làm đầy máu
#define CLEARSTATE_PROCESS_GETSCORE_TIME 1 // xử lí quy đổi thời gian dư ra điểm
#define CLEARSTATE_PROCESS_GETSCORE_HEART 2 // xử lí quy đổi thời gian dư ra điểm
#define CLEARSTATE_PROCESS_DONE 3 // xử lí xong

#define CLEARSTATE_LIMITTIMEWAIT_PROCESS_HEALTH 200 // thời gian chờ tăng mỗi đơn vị máu
#define CLEARSTATE_LIMITTIMEWAIT_PROCESS_GETSCORE_TIME 10 // thời gian chờ cộng điểm cho time dư
#define CLEARSTATE_LIMITTIMEWAIT_PROCESS_GETSCORE_HEART 200 // thời gian chờ cộng điểm cho hear dư

extern int Window_Width;
extern int Window_Height;

extern int MapWidth;
extern int MapHeight;


extern int ScreenColumn;
extern int ScreenRow;


// ID của Sprite, object
enum eType
{
	SIMON = 0,


	BRICK = 1,

	TORCH = 2,

	PORTAL = 50,

	MORNINGSTAR = 51,

	LARGEHEART = 52,

	UPGRADEMORNINGSTAR = 53,

	DAGGERITEM = 54,

	DAGGER = 55,

	FIRE = 56,

	HIT = 57,

	MONNEY = 58,

	CANDLE = 59,

	SMALLHEART = 60,

	STAIR_UP = 61,

	STAIR_DOWN = 62,

	BLACKKNIGHT = 63,

	ZOMBIE = 64,

	ZOMBIEZONE = 65,

	SPECIALBRICK = 66,

	SPECIALBRICKSMALL = 67,

	BAT = 68,

	HOLYWATER = 69,

	HOLYWATERITEM = 70,

	HIDDENOBJECT = 71,

	CROWN = 72,

	GHOST = 73,

	STOPWATCH = 74,

	STOPWATCHITEM = 75,

	BOOMERANG = 76,

	BOOMERANGITEM = 77,

	AXE = 78,

	AXEITEM = 79,

	MOVINGBRICK = 80,

	HUNCHBACK = 81,

	BONE = 82,

	SKELETON = 83,

	RAVEN = 84,

	PHANTOMBAT = 85,

	HIDDENOBJECTCREATEBOSS = 86,

	HIDDENOBJECTBLOCKCAMERA = 87,

	REDBALL = 88,

	EFFECT_MONEY_100 = 89,

	EFFECT_MONEY_1000 = 90

};


#endif
